# --- Clipboard History Daemon ---
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --watch --type image/png --type image/jpeg --type image/bmp --type image/svg+xml

# Wallpaper
exec-once = swww-daemon
exec-once = swww restore

# Programs
exec-once = hypridle
exec-once = waybar
exec-once = swaync

exec-once = systemctl --user start hyprpolkitagent # Open other partitions

# Start the keyring daemon
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
