##############################
### windows and workspaces ###
##############################

windowrule = suppress_event maximize, match:class .*
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
windowrule = float on, match:class ^(nwg-look)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)


#----------------opacity------------------------#
windowrule = opacity 0.8 0.8, match:class ^(spotify)$
windowrule = opacity 0.9 0.7, match:class ^(blueman-manager)$
windowrule = opacity 0.9 0.7, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = opacity 0.8 0.8, match:class ^(thunar)$
windowrule = opacity 0.9 0.9, match:class ^(zen)$
windowrule = opacity 1.0 1.0, match:class ^(virtualbox.*)$
windowrule = opacity 0.80 0.80, match:class ^(code)$
windowrule = opacity 0.80 0.80, match:class ^(vesktop)$

#---------------browser picture in picture----------------------------------------#
windowrule = float on, match:title ^(picture-in-picture)$
windowrule = pin on, match:title ^(picture-in-picture)$
windowrule = move (monitor_w*0.725) (monitor_h*0.70), match:title ^(picture-in-picture)$
windowrule = size 520 320, match:title ^(picture-in-picture)$


#---------------kitty update term-------------------------#
#---------------------------------------------------------#
windowrule = float on, match:title ^(PacUpdate)$
windowrule = center on, match:title ^(PacUpdate)$
windowrule = size 850 850, match:title ^(PacUpdate)$

#---------------kitty network term-------------------------#
#---------------------------------------------------------#
windowrule = float on, match:title ^(KittyNmtui)$
windowrule = center on, match:title ^(KittyNmtui)$
windowrule = size 800 600, match:title ^(KittyNmtui)$


#----------quickshell---------#
windowrule = float on, match:class ^(org.quickshell)$, match:title ^(quickshell settings)$
windowrule = size 800 600, match:class ^(org.quickshell)$, match:title ^(quickshell settings)$
windowrulev2 = center, match:class ^(org.quickshell)$, match:title ^(quickshell settings)$

#----------rofi---------------#
#-----------------------------#
layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.5, match:namespace rofi
layerrule = xray on, match:namespace rofi

#---------wlogout------------#
#----------------------------#
#layerrule = blur on, match:namespace logout_dialog


#-----------waybar-------------#
#------------------------------#
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.5, match:namespace waybar


#-----------swaync-------------#
#------------------------------#
layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-notification-window
